import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ttNormsPro = localFont({
  src: [
    {
      path: "../public/fonts/TTNormsPro-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/TTNormsPro-DemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/TTNormsPro-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-tt-norms-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ttNormsPro.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
